# Generated by Django 3.0.7 on 2020-08-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
    ]
