# Generated by Django 3.0.7 on 2020-08-20 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000000000000, unique=True),
            preserve_default=False,
        ),
    ]
