# Generated by Django 3.0.7 on 2020-08-21 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_visiters'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiters',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
